# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_newTest(self):
    self.driver.get("http://localhost:59757/")
    WebDriverWait(self.driver, 100).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "flutter-view")))
    self.driver.find_element(By.CSS_SELECTOR, "flutter-view").click()
    pw = self.driver.find_element(By.XPATH, "/html/body/flutter-view/flt-text-editing-host/form/input[1]")
    pw.send_keys("admin123")
    pw.send_keys(Keys.ENTER)

    WebDriverWait(self.driver, 100).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "flutter-view")))
    
    time.sleep(10)
  